version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
    commands:
      - echo Installing source NPM packages...
  build:
    commands:
      - echo Building Docker image...
      - docker build -t fastapi-crud-app .
      - $(aws ecr get-login --no-include-email --region ap-south-1)
      - docker tag fastapi-crud-app:latest 369281501673.dkr.ecr.ap-south-1.amazonaws.com/fastapi-crud-app:latest
      - docker push 369281501673.dkr.ecr.ap-south-1.amazonaws.com/fastapi-crud-app:latest
